FROM python:3-alpine
RUN apk add build-base
WORKDIR /mkdocs
RUN pip install mkdocs mkdocs-material mkdocs-windmill
# EXPOSE has only declaratory (and no configuratory!) effect:
EXPOSE 8000
# Serve mkdocs to all interfaces (not only localhost)!:
CMD ["mkdocs", "serve", "--dev-addr=0.0.0.0:8000"]
